spring.application.name=pdciae-back
spring.docker.compose.enabled=false
spring.data.mongodb.uri=mongodb+srv://servidor_render:8RuVUs2hKBCw0ceR@pdciae.kmjvbbb.mongodb.net/pdciae?retryWrites=true&w=majority&appName=PDCIAE
server.port=${PORT:8080}