spring.application.name=pdciae-back
spring.docker.compose.enabled=false
# Usa la variable MONGODB_URI si existe, si no, usa localhost
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/pdciae}
server.port=${PORT:8080}